"""add reject_reason

Revision ID: a28c35f99d36
Revises: bbe5c0808df1
Create Date: 2026-06-19 17:29:48.207464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28c35f99d36'
down_revision: Union[str, Sequence[str], None] = 'bbe5c0808df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('reject_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'reject_reason')
    # ### end Alembic commands ###
